[importer_direct_upload_blog] blog post for direct upload in importer is added
cloudera/hue pull request #2169
Opened 2021-05-26 08:00 UTC by agl29

## What changes were proposed in this pull request?

- blog post for importer direct upload

2021-05-26 11:37 UTC, romainr reviewed
Nice! 

A few small tweaks

2021-05-26 11:37 UTC, romainr commented on docs/gethue/content/en/posts/2021-05-26-importer-direct-upload.md
> +If you know the history of Hue then you must be familiar with the importer option in Hue. So basically earlier we could create a table from a file in different databases but there is one necessary co
FYI: s3 --> S3

2021-05-26 11:37 UTC, romainr commented on docs/gethue/content/en/posts/2021-05-26-importer-direct-upload.md
> +If you know the history of Hue then you must be familiar with the importer option in Hue. So basically earlier we could create a table from a file in different databases but there is one necessary co
1.2 is super old, please link to the last one, e.g. https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/HdfsDesign.html

2021-05-26 11:37 UTC, romainr commented on docs/gethue/content/en/posts/2021-05-26-importer-direct-upload.md
> +### Goal:
Remove all `:` in titles?

2021-05-26 11:40 UTC, pychheda requested changes
Hi Ayush,
Thanks for running this by me.

I have left comments and provided some suggestions.
Hope you find this helpful.
Best,
Priyanka

2021-05-26 11:40 UTC, pychheda commented on docs/gethue/content/en/posts/2021-05-26-importer-direct-upload.md
> +  Selection of dialect and auto field type guesses. You can edit the name and type of fields by clicking at the Fields section.
Suggested edit: You select a SQL dialect and Hue auto-detects the column data types. You can edit column names and their data type.

2021-05-26 11:40 UTC, pychheda commented on docs/gethue/content/en/posts/2021-05-26-importer-direct-upload.md
> +title: Importer direct upload
Suggest rewording to something like "Improved Hue Importer -- Select a file, choose a dialect, create a table".

2021-05-26 11:40 UTC, pychheda commented on docs/gethue/content/en/posts/2021-05-26-importer-direct-upload.md
> +![Importer direct upload steps app diagram](https://cdn.gethue.com/uploads/2021/05/Importer_direct_upload_app_diagram.png)
The blocks in the diagram look a bit inconsistent.
Could you please redo it? Suggestion:
Select a file --> Select a dialect (Hive, Impala, Phoenix, MySQL, ...) --> Review/Edit column names and data type --> Submit

Put the text in the boxes and keep the arrows blank.

2021-05-26 21:33 UTC, romainr approved these changes

2021-05-27 05:47 UTC, pychheda commented
Looks great! Thanks.

2021-05-27 05:57 UTC, pychheda commented on docs/gethue/content/en/posts/2021-05-26-improved-hue-importer-select-a-file-choose-a-dialect-create-a-table.md
> +Ayush from the Hue Team
LGTM.

2021-05-27 05:57 UTC, pychheda approved these changes

2021-05-27 06:08 UTC, merged