Hue Python3.8 upgrade
cloudera/hue pull request #2928
Opened 2022-07-16 18:40 UTC by ranade1

## What changes were proposed in this pull request?

- build
- oozie
- solr
- notebook
- filemanager
- backend

## How was this patch tested?

- tested on CentOS7/Postgres10 and other systems.

Please review [Hue Contributing Guide](https://github.com/cloudera/hue/blob/master/CONTRIBUTING.md) before opening a pull request.

2022-07-16 18:51 UTC, wing2fly approved these changes

2022-07-18 05:51 UTC, Harshg999 requested changes

2022-07-18 05:51 UTC, Harshg999 commented on desktop/libs/hadoop/src/hadoop/fs/hadoopfs.py
> +      try:
Why 2 try block? Can we add `finally` in one try block?

2022-07-18 07:27 UTC, JohanAhlen commented on desktop/core/requirements.txt
> +mysqlclient==2.1.0
Yes, this specific version indeed. For 1.2.x or earlier it's optionally CNRI which works for us.

2022-07-18 15:48 UTC, ranade1 commented on desktop/core/requirements.txt
> +Babel==2.5.3
@Harshg999 I think there was some problem with Babel on 2.9.1 version with Python3.8. I don't remember now. Once this change(with Babel==2.5.3) is in we will upgrade Babel to required version.

2022-07-18 17:48 UTC, ranade1 commented on desktop/core/requirements.txt
> +mysqlclient==2.1.0
removing mysqlclient as LGPLv2 is not permissible enough.

2022-07-18 22:25 UTC, wing2fly approved these changes

2022-07-18 22:26 UTC, merged