Initial Filechooser modal
cloudera/hue pull request #3023
Opened 2022-09-29 06:16 UTC by nidhibhatg

## What changes were proposed in this pull request?

Added a modal in the importer page as a initial file chooser component

2022-09-29 10:46 UTC, bjornalm requested changes
Really nice work! We are on our way, this is great.

2022-09-29 10:46 UTC, bjornalm commented on desktop/core/src/desktop/js/reactComponents/FileChooserComponent/FileChooserComponentButton/FileChooserComponentButton.tsx
> +const FileChooserComponentButton = (): JSX.Element => {
This component actually includes the whole FileChooserModal so calling it a button could be a bit misleading, for now perhaps we can call it `FileChooserWithButton` (there is no need to include "component" in any of the component or folder names).

2022-09-29 10:46 UTC, bjornalm commented on desktop/core/src/desktop/js/reactComponents/FileChooserComponent/FileChooserComponentButton/FileChooserComponentButton.tsx
> +import { Button } from 'antd';
nit: We can group the import statements with external libraries first and then our internal imports

2022-09-29 10:46 UTC, bjornalm commented on desktop/core/src/desktop/js/reactComponents/FileChooserComponent/FileChooserComponentButton/FileChooserComponentButton.tsx
> +    <div>
Unless you actually need this div you can remove it and use `<>...</>` instead

2022-09-29 10:46 UTC, bjornalm commented on desktop/core/src/desktop/js/reactComponents/FileChooserComponent/FileChooserComponentButton/FileChooserComponentButton.tsx
> +        File chooser component
I can imagine that we wanna reuse this button in multiple places, and possibly use different labels for the button, so you can add a prop this string. (In my upcoming i18n PR I will show how to combine i18n with props and default values)

2022-09-29 10:46 UTC, bjornalm commented on desktop/core/src/desktop/js/reactComponents/FileChooserComponent/FileChooserComponentButton/FileChooserComponentButton.tsx
> +  const [show, setShow] = useState(false);
As we move forward with the integration we probably want to lift the state into the page/component that actually uses the new FileChoser and we will be needing callbacks to handle the actions triggered by this component, but for now we can leave it.

2022-09-29 10:46 UTC, bjornalm commented on desktop/core/src/desktop/js/reactComponents/FileChooserComponent/FileChooserModal/FileChooserModal.tsx
> +    onClose();
We probably wanna add `onCancel` as its own callback in our component as well.

2022-09-29 10:46 UTC, bjornalm commented on desktop/core/src/desktop/js/reactComponents/FileChooserComponent/FileChooserModal/FileChooserModal.tsx
> +    onClose();
We probably wanna add `onOk` as its own callback in our component as well.

2022-09-29 10:46 UTC, bjornalm commented on desktop/core/src/desktop/js/reactComponents/FileChooserComponent/FileChooserModal/FileChooserModal.tsx
> +      title="Choose a file"
title should probably be prop wit default value in our component as well

2022-09-29 10:46 UTC, bjornalm commented on desktop/core/src/desktop/js/reactComponents/FileChooserComponent/FileChooserModal/FileChooserModal.tsx
> +      okText="Select"
prop for the okText also

2022-09-29 14:30 UTC, JohanAhlen commented on desktop/libs/indexer/src/indexer/templates/importer.mako
> +          !-->
I guess this one should be removed from the PR. You should keep it for development but let's not push it.

2022-10-28 07:51 UTC, JohanAhlen approved these changes
Nice! :-)

2022-10-28 11:35 UTC, bjornalm approved these changes
Great work!

2022-10-28 11:35 UTC, merged