Adding Task server backend changes for Hue
cloudera/hue pull request #3687
Opened 2024-04-09 21:14 UTC by ranade1

This change enables Hue backend server, following hue.ini parameters are needed.

[desktop]
enable_chunked_file_uploader=true
[filebrowser]
max_file_size_upload_limit=-1 # Bytes
[[task_server]]
enabled=True
beat_enabled=True
fetch_result_limit=20000
result_storage='{"BACKEND": "django.core.files.storage.FileSystemStorage", "properties": {"location": "./logs"}}' broker_url="redis://localhost:6379/0"
celery_result_backend="redis://localhost:6379/0"
celeryd_opts='--time-limit=300'
execution_storage='{"BACKEND": "django.core.cache.backends.locmem.LocMemCache", "LOCATION": "celery-hue"}'

Testing Done:
Tested file upload on HDFS, S3, ABFS, Ozone system

## What changes were proposed in this pull request?

- (Please fill in changes proposed in this fix)

## How was this patch tested?

- (Please explain how this patch was tested. Ex: unit tests, manual tests)
- (If this patch involves UI changes, please attach a screen-shot; otherwise, remove this)

Please review [Hue Contributing Guide](https://github.com/cloudera/hue/blob/master/CONTRIBUTING.md) before opening a pull request.

2024-04-10 01:18 UTC, wing2fly approved these changes

2024-04-10 06:53 UTC, JohanAhlen commented on apps/filebrowser/src/filebrowser/views.py
> +  if TASK_SERVER.ENABLED.get():
How about a unit test for this?

2024-04-10 20:01 UTC, athithyaaselvam approved these changes

2024-04-12 06:25 UTC, Harshg999 requested changes
Added few review comments, also possible to add few unit tests?

2024-04-12 06:25 UTC, Harshg999 commented on apps/filebrowser/src/filebrowser/views.py
> +    print("Uploading file to task server")
Remove print statement?

2024-04-12 06:25 UTC, Harshg999 commented on apps/filebrowser/src/filebrowser/views.py
> +    from filebrowser.tasks import upload_file_task, error_handler
Imports at the top or its a circular dependency?

2024-04-12 06:25 UTC, Harshg999 commented on apps/filebrowser/src/filebrowser/views.py
> +  if TASK_SERVER.ENABLED.get():
+1

2024-04-12 06:25 UTC, Harshg999 commented on apps/filebrowser/src/filebrowser/views.py
> +      result = "success"
Curious: Why we are doing this for hdfs?

2024-04-12 06:25 UTC, Harshg999 commented on desktop/core/src/desktop/lib/fs/ozone/upload.py
> +    if kwargs.get('chunk_size', None) != None:
Using `if kwargs.get('chunk_size'):` should simplify the check?

2024-04-12 06:25 UTC, Harshg999 commented on desktop/core/src/desktop/settings.py
> +  CELERY_TIMEZONE = "America/Los_Angeles"
Curious: Why not take it from Hue config?

2024-04-12 06:25 UTC, Harshg999 commented on desktop/libs/aws/src/aws/s3/upload.py
> +    if kwargs.get('chunk_size', None) != None:
Using `if kwargs.get('chunk_size'):` should simplify the check?

2024-04-12 06:25 UTC, Harshg999 commented on desktop/libs/azure/src/azure/abfs/upload.py
> +    self.destination = kwargs.get('dest', None)  # GET param avoids infinite looping
Only `kwargs.get('dest')` should be good?

2024-04-12 06:25 UTC, Harshg999 commented on desktop/libs/azure/src/azure/abfs/upload.py
> +    if kwargs.get('chunk_size', None) != None:
Using `if kwargs.get('chunk_size'):` should simplify the check?

2024-04-12 06:25 UTC, Harshg999 commented on desktop/libs/hadoop/src/hadoop/fs/upload.py
> +    if kwargs.get('filepath', None) != None:
Using `if kwargs.get('filepath'):` should simplify the check?

2024-04-12 06:25 UTC, Harshg999 commented on desktop/libs/hadoop/src/hadoop/fs/upload.py
> +    if kwargs.get('chunk_size', None) != None:
Using `if kwargs.get('chunk_size'):` should simplify the check?

2024-04-12 06:25 UTC, Harshg999 commented on desktop/libs/notebook/src/notebook/models.py
> +    #     LOG.debug('Skipping Task Server call %s' % name)
Nit: To remove?

2024-04-16 16:29 UTC, ranade1 commented
> Added few review comments, also possible to add few unit tests?

added a unit test.

2024-04-16 16:30 UTC, ranade1 reviewed
added a test case.

2024-04-16 17:45 UTC, Harshg999 approved these changes
LGTM!

2024-04-16 17:50 UTC, merged