[ui-storageBrowser]Implement UI for rename action
cloudera/hue pull request #3764
Opened 2024-06-24 11:06 UTC by nidhibhatg

## What changes were proposed in this pull request?

- Implement a rename modal and integrate it with the api
- Add tests to check for functionality and conditions.
- Update summary modal to call api only on modal open
- Add util functions to check for file systems. ( For eg: isS3, isGS and so on)

## How was this patch tested?

- UI Unit tests
- Manually

Please review [Hue Contributing Guide](https://github.com/cloudera/hue/blob/master/CONTRIBUTING.md) before opening a pull request.

2024-06-24 13:40 UTC, bjornalm reviewed
Nice work! I only have a couple of comments and questions

2024-06-24 13:40 UTC, bjornalm commented on desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserActions/StorageBrowserActions.test.tsx
> +    test('does not render view summary option when there are multiple records', async () => {
....option when there are multiple records **selected**?

You could rename also "mockRecord2" to be be more descriptive, e.g. mockTwoRecords

2024-06-24 13:40 UTC, bjornalm commented on desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserActions/StorageBrowserActions.test.tsx
> +    test('does not render view summary option when there are multiple records', async () => {
...selected

2024-06-24 13:40 UTC, bjornalm commented on desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserActions/StorageBrowserActions.test.tsx
> +      mockRecord.path = 'abfs://';
include the other ones roots?

2024-06-24 13:40 UTC, bjornalm commented on desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserActions/StorageBrowserActions.test.tsx
> +    test('does not render rename option when record is a a root folder', async () => {
... **selected** record...

2024-06-24 13:40 UTC, bjornalm commented on desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserActions/StorageBrowserActions.test.tsx
> +  describe('Summary option', () => {
For the scenarios when we do render the actions, why only check for the menu item not being null? I would test that I can actually click it that something is happening.

2024-06-24 13:40 UTC, bjornalm commented on desktop/core/src/desktop/js/utils/storageBrowserUtils.test.ts
> +    expect(isS3('s3a://')).toBe(true);
and `S3A://` etc if that could happen?

2024-06-25 20:46 UTC, bjornalm requested changes

2024-06-25 20:46 UTC, bjornalm commented on desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserActions/StorageBrowserActions.tsx
> +        onSuccessfulAction((oldKey: number) => oldKey + 1);
So what I meant what that this logic belongs in the parent
Can you move  `(oldKey: number) => oldKey + 1` to the parent component and here just call:
` onSuccessfulAction();`

2024-06-28 10:29 UTC, bjornalm approved these changes
LGTM

2024-06-28 10:29 UTC, bjornalm commented on desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserTable/StorageBrowserTable.tsx
> +              onSuccessfulAction={reloadData}
Now doesn't this feel better ;-)

2024-06-28 11:32 UTC, tabraiz12 approved these changes

2024-06-28 11:32 UTC, merged

2024-06-28 13:54 UTC, JohanAhlen commented on desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserActions/StorageBrowserActions.tsx
> +        !isOFSVol(selectedFilePath))
Nit: At some point move this to isFileOrFolder in StorageBrowserUtils

2024-06-28 13:54 UTC, JohanAhlen reviewed
LGTM!