[hive] Fix config issue in HS2 ZK discovery
cloudera/hue pull request #3829
Opened 2024-08-23 23:01 UTC by wing2fly

## What changes were proposed in this pull request?

-  update port number and Kerberos principle after switching to new active endpoint
-  sort the hs2 endpoints by Zookeeper sequence number so that recovered endpoint with new sequence number at the end
-  update cache logic 

## How was this patch tested?

- (Please explain how this patch was tested. Ex: unit tests, manual tests)
- (If this patch involves UI changes, please attach a screen-shot; otherwise, remove this)

Please review [Hue Contributing Guide](https://github.com/cloudera/hue/blob/master/CONTRIBUTING.md) before opening a pull request.

2024-08-23 23:16 UTC, amitsrivastava approved these changes

2024-08-23 23:20 UTC, quadoss approved these changes
LGTM

2024-08-26 08:32 UTC, Harshg999 approved these changes
Possible to add a unit test for this change?

2024-08-30 05:26 UTC, Harshg999 requested changes
@wing2fly Is the package-lock.json change required for this PR?
cc: @bjornalm

2024-09-04 01:33 UTC, wing2fly commented
Adding new fix for unit test and remove package-lock.json
cc: @Harshg999

2024-09-04 16:49 UTC, Harshg999 approved these changes
LGTM!

2024-09-04 17:50 UTC, merged