[ui-storagebrowser] add useWindowSize hook to get window size
cloudera/hue pull request #3930
Opened 2024-12-20 21:54 UTC by ramprasadagarwal

## What changes were proposed in this pull request?

- Whenever we need to set the dynamic height to the component, we need to listen the current window size with the offset to calculate the dynamic height. This hook solves that problem.

## How was this patch tested?

- Added unit tests

2025-01-06 12:01 UTC, JohanAhlen reviewed
I know all you did was introduce the hook which is nice but..

I'm not a big fan of setting heights using JS. This problem is solvable using CSS layout so let's do that instead.

2025-01-07 09:37 UTC, nidhibhatg approved these changes
LGTM!

2025-02-03 14:41 UTC, bjornalm requested changes

2025-02-03 14:41 UTC, bjornalm commented on desktop/core/src/desktop/js/utils/hooks/useWindowSize/useWindowSize.ts
> +    window.addEventListener('resize', handleResize);
Please use the ResizeObserver API instead of window so that this code is triggered if parent containers get resized without and actual resize of the window.

2025-02-03 14:42 UTC, bjornalm commented
> I know all you did was introduce the hook which is nice but..
> 
> I'm not a big fan of setting heights using JS. This problem is solvable using CSS layout so let's do that instead.

I think this is a limitation of the underlying antd table, at least I had the same issue when creating the infinite scroll table.

2025-03-12 10:30 UTC, bjornalm approved these changes
nice work, just make sure to change the name of the hook

2025-03-12 10:30 UTC, merged